package ProyectoDad.LaCruzVerde;

import java.util.Calendar;
import java.util.Random;

import io.netty.handler.codec.mqtt.MqttConnectReturnCode;
import io.netty.handler.codec.mqtt.MqttQoS;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Promise;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.Json;
import io.vertx.mqtt.MqttClient;
import io.vertx.mqtt.MqttClientOptions;
import io.vertx.mqtt.impl.MqttClientImpl;

import types.actuador_valor;

public class MqttClientVerticle_Actuador_valor_LaCruzVerde extends AbstractVerticle{

	private String classInstanceId;

	public void start (Promise<Void> promise) {
		MqttClientOptions mqttClientOptions	= new MqttClientOptions();
		mqttClientOptions.setAutoKeepAlive(true);
		mqttClientOptions.setAutoGeneratedClientId(false);
		mqttClientOptions.setClientId(classInstanceId);
		mqttClientOptions.setConnectTimeout(10000);
		mqttClientOptions.setKeepAliveTimeSeconds(10);
		mqttClientOptions.setReconnectAttempts(10);
		mqttClientOptions.setReconnectInterval(5000);
		mqttClientOptions.setUsername("mqttbroker");
		mqttClientOptions.setPassword("mqttbrokerpass");
		MqttClient mqttClient = new MqttClientImpl(vertx, mqttClientOptions);

		mqttClient.publishHandler(messageReceivedHandler -> {
			System.out.println(messageReceivedHandler.payload().toString());
		});

		//TOPIC ACTUADOR_VALOR --> introduce si esta funcionando un actuador en la bbdd cada cierto tiempo
		mqttClient.connect(1885, "localhost", handler -> {
			if(handler.result().code() == MqttConnectReturnCode.CONNECTION_ACCEPTED) {
				mqttClient.subscribe(MqttServerVerticle_LaCruzVerde.TOPIC_ACTUADOR_VALOR, MqttQoS.AT_LEAST_ONCE.value(), handlerSubscribe -> {
					if(handlerSubscribe.succeeded()) {
						System.out.println(classInstanceId + " suscrito a " + MqttServerVerticle_LaCruzVerde.TOPIC_ACTUADOR_VALOR + " topic");
						vertx.setPeriodic(10000, periodic -> {
							Random random = new Random();
							actuador_valor actuador_valor = new actuador_valor(random.nextInt(100), 2, random.nextBoolean(), Calendar.getInstance().getTimeInMillis());
							mqttClient.publish(MqttServerVerticle_LaCruzVerde.TOPIC_ACTUADOR_VALOR, Buffer.buffer(Json.encodePrettily(actuador_valor)),
									MqttQoS.AT_LEAST_ONCE, false, true);
						});
					}else {
						System.out.println(classInstanceId + " no suscrito a " + MqttServerVerticle_LaCruzVerde.TOPIC_ACTUADOR_VALOR + " topic");
					}
				});
			}else {
				System.out.println("Error: " + handler.result().code());
			}
		});

	}
}