package ProyectoDad.LaCruzVerde;

import java.util.Calendar;
import java.util.Random;

import io.netty.handler.codec.mqtt.MqttConnectReturnCode;
import io.netty.handler.codec.mqtt.MqttQoS;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Promise;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.Json;
import io.vertx.mqtt.MqttClient;
import io.vertx.mqtt.MqttClientOptions;
import io.vertx.mqtt.impl.MqttClientImpl;

import types.dispositivo;

public class MqttClientVerticle_Dispositivo_LaCruzVerde extends AbstractVerticle{

	private String classInstanceId;

	public void start (Promise<Void> promise) {
		MqttClientOptions mqttClientOptions	= new MqttClientOptions();
		mqttClientOptions.setAutoKeepAlive(true);
		mqttClientOptions.setAutoGeneratedClientId(false);
		mqttClientOptions.setClientId(classInstanceId);
		mqttClientOptions.setConnectTimeout(10000);
		mqttClientOptions.setKeepAliveTimeSeconds(10);
		mqttClientOptions.setReconnectAttempts(10);
		mqttClientOptions.setReconnectInterval(5000);
		mqttClientOptions.setUsername("mqttbroker");
		mqttClientOptions.setPassword("mqttbrokerpass");
		MqttClient mqttClient = new MqttClientImpl(vertx, mqttClientOptions);

		mqttClient.publishHandler(messageReceivedHandler -> {
			System.out.println(messageReceivedHandler.payload().toString());
		});

		//TOPIC DISPOSITIVO --> cuando se conecte un nuevo dispositivo, deberiamos poder introducirle los parametros que necesita 
		//						para cuidar la planta, este canal introduce en la bbdd los parametros de este nuevo dispositivo
		//						La idea es cambiar que sea periodicamente para que desde la app asignemos unn dispositivo a una 
		//						planta y lo pongamos en marcha
		mqttClient.connect(1885, "localhost", handler -> {
			if(handler.result().code() == MqttConnectReturnCode.CONNECTION_ACCEPTED) {
				mqttClient.subscribe(MqttServerVerticle_LaCruzVerde.TOPIC_DISPOSITIVO, MqttQoS.AT_LEAST_ONCE.value(), handlerSubscribe -> {
					if(handlerSubscribe.succeeded()) {
						System.out.println(classInstanceId + " suscrito a " + MqttServerVerticle_LaCruzVerde.TOPIC_DISPOSITIVO + " topic");
						vertx.setPeriodic(10000, periodic -> {
							Random random = new Random();
							dispositivo dispositivo = new dispositivo(random.nextInt(100), random.nextInt(200)+"."+random.nextInt(200)+"."+random.nextInt(200)+"."+random.nextInt(200), 
									"CruzVerde_Aloevera", 1, Calendar.getInstance().getTimeInMillis());
							mqttClient.publish(MqttServerVerticle_LaCruzVerde.TOPIC_DISPOSITIVO, Buffer.buffer(Json.encodePrettily(dispositivo)),
									MqttQoS.AT_LEAST_ONCE, false, true);
						});
					}else {
						System.out.println(classInstanceId + " no suscrito a " + MqttServerVerticle_LaCruzVerde.TOPIC_DISPOSITIVO + " topic");
					}
				});
			}else {
				System.out.println("Error: " + handler.result().code());
			}
		});

	}
}
