package ProyectoDad.LaCruzVerde;

import io.netty.handler.codec.mqtt.MqttConnectReturnCode;
import io.netty.handler.codec.mqtt.MqttQoS;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Promise;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.Json;
import io.vertx.mqtt.MqttClient;
import io.vertx.mqtt.MqttClientOptions;
import io.vertx.mqtt.impl.MqttClientImpl;

import types.planta;

public class MqttClientVerticle_Planta_LaCruzVerde extends AbstractVerticle{

	private String classInstanceId;

	public void start (Promise<Void> promise) {
		MqttClientOptions mqttClientOptions	= new MqttClientOptions();
		mqttClientOptions.setAutoKeepAlive(true);
		mqttClientOptions.setAutoGeneratedClientId(false);
		mqttClientOptions.setClientId(classInstanceId);
		mqttClientOptions.setConnectTimeout(10000);
		mqttClientOptions.setKeepAliveTimeSeconds(10);
		mqttClientOptions.setReconnectAttempts(10);
		mqttClientOptions.setReconnectInterval(5000);
		mqttClientOptions.setUsername("mqttbroker");
		mqttClientOptions.setPassword("mqttbrokerpass");
		MqttClient mqttClient = new MqttClientImpl(vertx, mqttClientOptions);

		mqttClient.publishHandler(messageReceivedHandler -> {
			System.out.println(messageReceivedHandler.payload().toString());
		});

		//TOPIC PLANTA --> Desde la app web deberiamos poder introducir en la bbdd una nueva planta para cuidar
		//				   La idea es cambiar que sea periodicamente para que sea simplemente cuando se lo mandemos desde
		//				   la app
		mqttClient.connect(1885, "localhost", handler -> {
			if(handler.result().code() == MqttConnectReturnCode.CONNECTION_ACCEPTED) {
				mqttClient.subscribe(MqttServerVerticle_LaCruzVerde.TOPIC_PLANTA, MqttQoS.AT_LEAST_ONCE.value(), handlerSubscribe -> {
					if(handlerSubscribe.succeeded()) {
						System.out.println(classInstanceId + " suscrito a " + MqttServerVerticle_LaCruzVerde.TOPIC_PLANTA + " topic");
						vertx.setPeriodic(10000, periodic -> {
							planta planta = new planta(1, "Aloevera", 22, 25, 5);
							mqttClient.publish(MqttServerVerticle_LaCruzVerde.TOPIC_PLANTA, Buffer.buffer(Json.encodePrettily(planta)),
									MqttQoS.AT_LEAST_ONCE, false, true);
						});
					}else {
						System.out.println(classInstanceId + " no suscrito a " + MqttServerVerticle_LaCruzVerde.TOPIC_PLANTA + " topic");
					}
				});
			}else {
				System.out.println("Error: " + handler.result().code());
			}
		});		

	}
}
